Themeswitcher
ComputerScienceHouse/blog pull request #56
Opened 2018-04-11 01:31 UTC by mxmeinhold

2018-04-12 13:23 UTC, devinmatte submitted a review, later dismissed

2018-04-30 22:44 UTC, RamZallan requested changes

2018-04-30 22:44 UTC, RamZallan commented on _posts/2018-04-09-themeswitcher.md
> +Themeswitcher requires SSO on principle, so it can determine who's theme to return.
`who's` -> `whose`

2018-04-30 22:44 UTC, RamZallan commented on _posts/2018-04-09-themeswitcher.md
> +description: A webservice that allows a user to select a bootstrap theme and an api to serve that theme to other sites that desire to implement themeswitcher.
could you add an image attribute w/ a screenshot of the project? Should be in the form:
`image: https://urlgoes.here/`

2018-06-14 03:32 UTC, mxmeinhold commented
CI is failing due to openshift being down. Appears all of the links I've used passed.

2018-06-14 03:42 UTC, csssuf requested changes
Looks good but is a little short/abrupt. If you feel there really isn't anything else to say it's okay, but if you have stuff you could expand on that'd be better.

2018-06-14 03:42 UTC, csssuf commented on _posts/2018-04-09-themeswitcher.md
> +[Themeswitcher](https://themeswitcher.csh.rit.edu) is a service that allows a user to select a bootstrap theme to be applied across the various internal CSH services.
`s/bootstrap/Bootstrap/`

2018-06-14 03:42 UTC, csssuf commented on _posts/2018-04-09-themeswitcher.md
> +Which is why Themeswitcher is written with Node.js.
Sentence fragment, but if you think it's necessary for the right tone it can stay.

2018-06-14 03:42 UTC, csssuf commented on _posts/2018-04-09-themeswitcher.md
> +When another service wishes to load a user's theme, it must simply make a style reference to `themeswitcher.csh.rit.edu/api/get` and the logged in user's theme will be returned as a redirect to s3.
Would be cool to have a small snippet showing exactly how it's used.
`s/logged in/current/`
`s/s3/CSH S3/`

2019-01-20 17:17 UTC, closed without merging